# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDZ_CXPU7rxJ3d4n5O44YllEDO37fPgL
"""

#Ticket Price calculator.
#Calculates price based on booking day and age of the user.
#Special 20% discount is applied from Monday through Thursday.
#This script validates user age input if it falls in the range of 0 - 120
#and validates date which should be any date from current date through next 3 months

#User inputs : (1) Date for ticket booking and (2)Age for price discount

from datetime import datetime,timedelta

#discountPercentage=0.0

# 1. Get user age
while True:
    try:
        userAge = int(input("Enter user age: "))
        if 0 <= userAge <= 120:
            break
        print("Please enter a valid age between 0 and 120.")
    except ValueError:
        print("Invalid input. Please enter a whole number.")

#Price based on input age
if userAge < 12:
    ticketPrice = 15  # Child price
elif userAge >= 65:
    ticketPrice = 12  # Senior price
else:
    ticketPrice = 20  # Adult price


# 2. Get date of booking
while True:
    date_input = input("Enter date of booking (MM-DD-YYYY): ").strip()
    try:
        date_object = datetime.strptime(date_input, "%m-%d-%Y")
        #check if the date is current or future date only
        if date_object.date() < datetime.today().date():
            print("Please enter current or future date!")
            continue

        #check if date is not later than 3 months from current date
        max_booking_date = datetime.today().date() + timedelta(days=90)
        if date_object.date() > max_booking_date:
            print(f"Invalid date! Bookings are only allowed up to 3 months in advance (until {max_booking_date.strftime('%m-%d-%Y')}).")
            continue

        day_name = date_object.strftime("%A")
        print("----------------------------------------------")
        print(f"Success! Booking confirmed for : {date_input}")

        # 3. Check and Apply 20% Weekday Discount
        weekday_discount_days = ["Monday", "Tuesday", "Wednesday", "Thursday"]
        if day_name in weekday_discount_days:
            discount_applied = ticketPrice * 0.20
            print(f"20% discount applied for {day_name} booking! Original Price was ${ticketPrice}")
            ticketPrice = ticketPrice - discount_applied
        break

    except ValueError:
            print("Invalid date format. Please type in MM-DD-YYYY format!")


print(f"Final ticket price  : ${ticketPrice:.2f}")

#Example Run 1:
""" Enter user age: hhj
Invalid input. Please enter a whole number.
Enter user age: 11
Enter date of booking (MM-DD-YYYY): 09-26-2027
Invalid date! Bookings are only allowed up to 3 months in advance (until 12-22-2026).
Enter date of booking (MM-DD-YYYY): 09-23-2026
----------------------------------------------
Success! Booking confirmed for : 09-23-2026
20% discount applied for Wednesday booking! Original Price was $15
Final ticket price  : $12.00

 """
#Example Run 2:
""" Enter user age: 67
Enter date of booking (MM-DD-YYYY): 09-24-2026
----------------------------------------------
Success! Booking confirmed for : 09-24-2026
20% discount applied for Thursday booking! Original Price was $12
Final ticket price  : $9.60
 """